# -- FAST-PROTOTYPING: Tests on Windows -- Until tests are OK.
# BASED ON: tests.yml
# SUPPORTED PYTHON VERSIONS: https://github.com/actions/python-versions

name: tests-windows
on:
  workflow_dispatch:
  push:
    branches: [ "main", "release/**" ]
    paths:
      - ".github/**/*.yml"
      - "**/*.py"
      - "**/*.feature"
      - "py.requirements/**"
      - "*.cfg"
      - "*.ini"
      - "*.toml"
  pull_request:
    types: [opened, reopened, review_requested]
    branches: [ "main" ]
    paths:
      - ".github/**/*.yml"
      - "**/*.py"
      - "**/*.feature"
      - "py.requirements/**"
      - "*.cfg"
      - "*.ini"
      - "*.toml"


# -- TEST BALLOON: Fix encoding="cp1252" problems by using "UTF-8"
env:
  PYTHONUTF8: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.12", "3.11", "3.10", "3.9"]
    steps:
      - uses: actions/checkout@v4
      # DISABLED: name: Setup Python ${{ matrix.python-version }} on platform=${{ matrix.os }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'py.requirements/*.txt'
      # -- DISABLED:
      # - name: Show Python version
      #   run: python --version
      - name: Install Python package dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install --upgrade -r py.requirements/ci.github.testing.txt
          pip install -e .
      - name: Run tests
        run: pytest
      - name: Run behave tests
        run: |
          behave --format=progress3 features
          behave --format=progress3 tools/test-features
          behave --format=progress3 issue.features
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test reports
          path: |
            build/testing/report.xml
            build/testing/report.html
        if: ${{ job.status == 'failure' }}
        # MAYBE: if: ${{ always() }}
      - name: Upload behave test reports
        uses: actions/upload-artifact@v3
        with:
          name: behave.reports
          path: build/behave.reports/
