# -- TEST-VARIANT: pypy-27 on ubuntu-latest
# BASED ON: tests.yml

name: tests-pypy27
on:
  workflow_dispatch:
  push:
    branches: [ "main", "release/**" ]
    paths:
      - ".github/**/*.yml"
      - "**/*.py"
      - "**/*.feature"
      - "py.requirements/**"
      - "*.cfg"
      - "*.ini"
      - "*.toml"
  pull_request:
    types: [opened, reopened, review_requested]
    branches: [ "main" ]
    paths:
      - ".github/**/*.yml"
      - "**/*.py"
      - "**/*.feature"
      - "py.requirements/**"
      - "*.cfg"
      - "*.ini"
      - "*.toml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["pypy-2.7"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'py.requirements/*.txt'

      - name: Install Python package dependencies
        run: |
           python -m pip install -U pip setuptools wheel
           pip install --upgrade -r py.requirements/ci.github.testing.txt
           pip install -e .
      - name: Run tests
        run: pytest
      - name: Run behave tests
        run: |
          behave --format=progress features
          behave --format=progress tools/test-features
          behave --format=progress issue.features
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test reports
          path: |
            build/testing/report.xml
            build/testing/report.html
            # MAYBE: build/behave.reports/
        if: ${{ job.status == 'failure' }}
        # MAYBE: if: ${{ always() }}
